### ISSUE TITLE
nvue报错，能正常显示二维码，控制台报错

### ISSUE THREAD

**Issue by xubo5200** [Sansnn/uQRCode#11]
<template>

	<view class="content">
		
		<u-qrcode ref="qrcode" canvas-id="qrcode" :size="size" :value="text" ></u-qrcode>

	</view>

</template>

reportJSException >>>> exception function:gcanvas setBackGround for android view, exception:WX_RENDER_ERR_TEXTURE_SETBACKGROUND: TextureView doesn't support displaying a background drawable!

**Comment by Sansnn** [comment]
nvue就是这样的，官方案例也会报这个错，这个不影响
