### ISSUE TITLE
feature of text logo

### ISSUE THREAD

**Issue by CoderMonkie** [Sansnn/uQRCode#14]
老师你好，感谢提供好用的`uQRCode` 

目前，二维码中间可以显示一个 logo 图片，

如果能显示指定文字就更好了

请问有没有考虑实现可以显示`文字` 的功能呢？

**Comment by Sansnn** [comment]
如果是使用原生js+canvas方式，那么可以在调用`uqrcode.draw`方法之后，继续使用当前`canvas`上下文继续操作画布，这样就可以实现绘制文字在二维码上。组件方式的话暂时得先自行扩展一下了。
