### ISSUE TITLE
feature of filename

### ISSUE THREAD

**Issue by CoderMonkie** [Sansnn/uQRCode#15]
老师你好，感谢提供好用的`uQRCode` 

目前，二维码可以下载为图片，

如果在下载时（调用 `save`方法）能指定图片的文件名就更好了

请问有没有考虑实现可以`指定文件名`的功能呢？

**Comment by Sansnn** [comment]
Web端可在uqrcode.vue文件中`save`方法内找到注释为`// 设置下载的文件名，默认是'下载'`，然后扩展`props`给到此处即可。可以暂时使用这个方法实现。
