### ISSUE TITLE
vue3无法启动

### ISSUE THREAD

**Issue by shunyue1320** [Sansnn/uQRCode#16]
## 复现流程
1. https://ext.dcloud.net.cn/plugin?id=1287

2. 使用HBuilderX导入示例项目 选择 vue3

3. 运行到手机报错

<img width="1047" alt="image" src="https://user-images.githubusercontent.com/47295879/183800079-3ce2fdcd-917e-4696-9779-06e13fd6fcd1.png">

**Comment by Sansnn** [comment]
示例项目暂不支持vue3

**Comment by shunyue1320** [comment]
> 示例项目暂不支持vue3

现在 vue3 还白屏吗？

**Comment by Sansnn** [comment]
vue3已修复，vue3示例项目也上传到GitHub了，在uni-app目录下，你可以看看

**Comment by shunyue1320** [comment]
感谢大佬🙏
