### ISSUE TITLE
[问题]: 请问有对应的 @types 包吗？

### ISSUE THREAD

**Issue by kvii** [Sansnn/uQRCode#28]
在 vue 工程中用下面的方式导入后：

```js
import UQRCode from 'uqrcodejs';
```

IDE 飘红，报错无法找到模块“uqrcodejs”的声明文件。请问方便维护一下对应的 @types 包吗。

**Comment by Sansnn** [comment]
目前没有@types包，可以在项目中声明一下`declare module "uqrcodejs";`用于解决IDE的报错提示
