### ISSUE TITLE
微信小程序真机出现的问题截图

### ISSUE THREAD

**Issue by Yun-cong** [Sansnn/uQRCode#4]
有些时候生成的二维码错误，连定位角都错误，还有些时候出现黑色。很多时候第一次生成会出错，然后刷新就会好，但多刷几下又有问题，贴了一段会员码的代码，用的生成的图片链接展示的。

![image](https://user-images.githubusercontent.com/48848359/127252878-7b208fd5-9a69-4b2e-a9bd-a802b6e01fb4.png)
![image](https://user-images.githubusercontent.com/48848359/127252562-bfc75757-599c-4336-9b82-5a3b5dae30d5.png)
![image](https://user-images.githubusercontent.com/48848359/127252602-d2439e4c-d612-4dd7-a6f4-880d3ceca6bc.png)

**Comment by Sansnn** [comment]
``2.0.2`` 新增了一个延迟绘制的属性 ``enableDelay``，尝试一下将它设置为 ``true`` 再进行生成看看有没有解决问题。

**Comment by zhous1993** [comment]
遇到同问题 真机调试也没有问题 体验版就有问题

**Comment by zzv123** [comment]
我也遇到了这个问题，在小程序模拟器可以，真机就会经常性出现乱码
