### ISSUE TITLE
遍历使用uQRCode.make问题

### ISSUE THREAD

**Issue by LausanneChan** [Sansnn/uQRCode#7]
我有个一个数组,里面一共有9个数据,我在success里面push"res"到新数组,但是我用手机扫一下二维码,全部二维码都是数组里面的最后一个数据. 本人虚心请教 感谢!!!

**Comment by Sansnn** [comment]
示例里面有批量生成，代码微调一下即可，已给你写好注释

```html
<text class="title">批量生成</text>
<view class="qrcode-box" v-for="(item, index) in qrcodeList" :key="index">
  <uqrcode :cid="'batchQRCode' + index" ref="batchQRCode" :text="item" :size="256" :margin="10" background-color="#FFFFFF" foreground-color="#000000"></uqrcode>
  <text class="text">{{ item }}</text>
</view>
<button class="button" type="primary" @tap="saveBatch">批量保存</button>
```
```javascript
methods: {
    saveBatch() {
      this.$refs.batchQRCode.forEach((ref, index) => {
        setTimeout(() => {
          // 这里把ref.save换成ref.toTempFilePath可获取到临时文件，获取到临时文件后push到数组里即可
          ref.save({
            success: res => {
              uni.showToast({
                icon: 'none',
                title: `${res.msg} (${index + 1})`
              });
            }
          });
        }, index * 500); // 这个延时可以不要
      });
    }
}
```

**Comment by LausanneChan** [comment]
> 示例里面有批文，代码方便一下，已经给你写好了
> 
> ```
> < text  class =" title " : cidclass- >类生成</ text > 
> < v-for =" (item,index)in qrcodeList " : cikey  = " index " > < qqrcode = " ' batchQRCode' + 索引“​​ ref = batchQRCode ” :text =" item " :size =" 256 " :margin ="10 "背景色
>    =" #FFFFFF "前景色=" #000000 " > </ uqrcode > 
>   < text  class =" text " > {{item}} </ text > 
> </ view > 
> < button  class =" button " type =" primary " @ tap =" saveBatch " >批量保存</ button >
> ```
> 
> ```js
> 方法：{ 
>     saveBatch ( )  {
>       这个. $refs 。批量二维码。forEach ( ( ref ,  index )  =>  { 
>         setTimeout ( ( )  =>  { 
>           // 这里把ref.save换成ref.toTempFilePath可获取到临时文件，获取到临时文件后推送到临时文件中即可获取
>           ref . save ( {
>             成功：res  =>  { 
>               uni .showToast （{图标：
>                 'none ' ，标题：`
>                 ${水库。味精} ( ${索引 +  1 } )`
>               }); 
>             }
>           }); 
>         }, 索引 * 500);  //这个可以
>       不要}) }}
>     
> ```

非常感谢老师!!!我去试试,真的感谢感谢感谢!
